### ISSUE TITLE
Enchantment misinterpretation

### ISSUE THREAD

**Issue by Laifsyn** [dsfhdshdjtsb/enchantments#13]
![image](https://user-images.githubusercontent.com/99366187/156443529-ad388f15-aa85-40a1-9a48-cca8be4c7ffa.png)

`    @Override
    public int getMinPower(int level) {
        return 10 + 20 * (level - 1);
    }`
   So according to what's in the[ source code](https://github.com/dsfhdshdjtsb/enchantments/blob/1.18/src/main/java/com/dsfhdshdjtsb/CombatEnchants/enchantments/DeflectEnchantment.java), the formula is 10+20(Level-1) instead of 10(Level) %

**Comment by Laifsyn** [comment]
![image](https://user-images.githubusercontent.com/99366187/156447795-553bfe61-ab93-4e86-bd78-698ffc914b8f.png)
[`Combo`](https://github.com/dsfhdshdjtsb/enchantments/blob/1.18/src/main/java/com/dsfhdshdjtsb/CombatEnchants/enchantments/ComboEnchantment.java) also has a mis-interpretation on its description.
```
    @Override
    public int getMinPower(int level) {
        return 5 + (level - 1) * 8;
    }
```
The result should be _Each hit will apply the mark effect for 5 + (level -1) * 8 seconds_

**Comment by Laifsyn** [comment]
Well, according to what's I'm seeing. Idk of any other backend code that further edits the results

**Comment by dsfhdshdjtsb** [comment]
the get min power level method determines the minimum power level required by the enchanting table for the enchantment to appear. The code for the actual deflection is handled in the living entity mixin

if(source.isProjectile()) {
            int deflectLevel = EnchantmentHelper.getLevel(CombatEnchants.DEFLECT, this.getEquippedStack(EquipmentSlot.CHEST));
            if (deflectLevel != 0 && this.random.nextInt(100) < deflectLevel * 10) {
                if(this.world instanceof ServerWorld)
                {
                    ((ServerWorld) this.world).spawnParticles(ParticleTypes.POOF, this.getX(), this.getBodyY(0.5D), this.getZ(), 5, 0.3, 0.5, 0.3, 0.0D);
                }
                cir.cancel();
            }
        }
