### ISSUE TITLE
Suggestion: How to make people to use suicide enchant

### ISSUE THREAD

**Issue by Laifsyn** [dsfhdshdjtsb/enchantments#14]
**Describe the suggestion you'd like**
a list of custom(?) messages to send when someone kills themselves using the suicide enchantment
and probly another set in case the manage to kill someone/mob/anyone. And also make Suicide a leveled enchant, which will increase the damage output(capping to insta kill maybe at level 7?) preferably in a linearly increase in case some heavier modded environments have better armor so they can dial up the levels to their preferences

**Describe the reasoning for the suggestion. Balance? Fixing a frustrating mechanic? New Idea?**
Make the trolling funnier

**Additional context**
Fails to kill someone: "Player(owner) didn't want to live in the same world with Player2(target)"

**Comment by dsfhdshdjtsb** [comment]
Great suggestion. However, I don't want to make suicide too strong to the point where ungeared players can just instant kill max geared players. I will consider adding more levels next patch(along with death messages if I can figure it out)
![image](https://c.tenor.com/wVPwQbNesqYAAAAd/no-more-trolling-no-more-trolling-trollge.gif)

**Comment by Laifsyn** [comment]
If suicide too strong is a no, then would it be possible to dial its damage through config? Because I've  been in some testings in a modded environment, and I'm losing negative hp tanking a mob's damage. that's why linearly scaling damage. Default 5 levels equals roughly to End Crystal explosion.(or even 1 TNT as default damage value).
Reason emphasis on a linearly scaling damage is because in Fabric there's a mod that allows you to ramp up an enchantment's dmg up to ~2^31 levels. so <damage per level> = <ConfigDamage>/5. That way it will stay balanced, but highly configurable. Balanced because people would just dial up the enchant level instead of the damage. And there's gotta be a hard zealoutness to, let's say enchant a lv. 20 suicide. And also works as a EXP dumpster method imo. Like Never stop grinding
