### ISSUE TITLE
[Feature Request] Add ability to enable/disable enchantments from appearing in enchantment tables, treasure, villagers, mob equipment and loot

### ISSUE THREAD

**Issue by elhertz** [dsfhdshdjtsb/enchantments#18]
Hey! I've requested some of this features to a couple of devs before. I think it should greatly improve the experience with the mod.

So, in my use case, I like to make some of the new enchantments as treasure-only or as a custom boss' loot to make them rare, some can be crafted with [NbtCrafting](https://www.curseforge.com/minecraft/mc-mods/nbt-crafting), others can be traded with villagers, then the rest that I consider not that broken/OP can still be obtained in the enchantment table.

Now, this request is super specific and it would only benefit me (_a server owner/modpack maker_) because I don't think casual players would make use of it. Still, I think it's a really good tool for us (_server owners/modpack makers_) to give our players a better experience with enchanting.

Specific info about my request:
- General: ability to disable enchantments from initializing (_I don't know if that's possible but it would be a good way to prevent enchantments even from appearing in mods like [REI](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)_)
- Enchantment table: ability to enable-only/disable certain enchantments from appearing in the enchantment table.
- Treasure: ability to enable-only/disable certain enchantments from appearing in treasure loot tables. 
There's this function that minecraft uses to assign a random enchantment to an enchanted book, armor, weapon, or tool. It includes all the enchantments afaik. It's called "`minecraft:enchant_randomly`". I use lots of mods/datapacks that add new structures and mobs and it's a pain having to manually edit 500 loot tables everytime I add new enchantments.
- Villager trading: ability to enable-only/disable certain enchantments from appearing in villager trades.
- Mob equipment and mob loot: enable-only/disable certain enchantments from appearing in mob equipment and loot (_I remember there was this mod that allowed you to disable enchantments but they would still appear in mob armor and weapons so I had to deal with the fact that you can't even disable them using loot tables_) 

Note: what's that about "enable-only"? With that setting you wouldn't need to go and disable enchantments one by one when for example you only need it as "treasure only".

Here are some old requests I made to other enchantment mods, the code might be useful to you:
https://github.com/StrikerRockers-Mods/VanillaTweaksFabric/issues/6
https://github.com/Tigereye504/spellbound/issues/12
https://github.com/herb-mc/extra_enchants/issues/12

This it a lot of work so I wouldn't mind if you just want to keep your mod as simple as possible.
Feel free to ask me more questions. Sometimes my english makes no sense. Thanks!

edit: fixed some typos

**Comment by dsfhdshdjtsb** [comment]
Ok, I think I understand what you are requesting, which is basically a greatly expanded config file. I think its a great idea, but it'll take me a long time to add all those features and options. I'll consider adding it if I get more time but I am a little tight on time atm.

**Comment by elhertz** [comment]
> Ok, I think I understand what you are requesting, which is basically a greatly expanded config file. I think its a great idea, but it'll take me a long time to add all those features and options. I'll consider adding it if I get more time but I am a little tight on time atm.

You could also make a simpler version. My request is too big haha 
Thank you
