### ISSUE TITLE
Suggestion: Configurable Level requirements

### ISSUE THREAD

**Issue by Mr-Syntax** [dsfhdshdjtsb/enchantments#22]
So plain and simple it would be really nice if you could configure the level requirment cap for max level enchants

Example:

the current cap is level 30 which will cost you 3 levels, i want to configure it to be at 60 instead
so you can get unbreaking 3 at level 60 instead of it being at level 30
and the amount of bookshelves required around the enchantment table should also be doubled when doing this

i really like the enchants but they are pretty OP and i think this would be an easy to balance it out so people can make the best experience for their pack

ive included your mod in this pack
https://www.curseforge.com/minecraft/modpacks/hack-n-craft

**Comment by dsfhdshdjtsb** [comment]
Thanks for including my mod in your modpack. As for changing the level cap, I think that would be best solved by using another mod with combat enchants together, as my mod would be too all-encompassing if it also changed enchanting mechanics. All my mod does is add new enchantments to the game, I'm sure there are other mods that can change the mechanics of enchanting.
