### ISSUE TITLE
Please Add The Enchantment Combining Multipliers In the Wiki Entries for the Enchantments

### ISSUE THREAD

**Issue by tanman** [dsfhdshdjtsb/enchantments#23]
For example- see this Minecraft wiki page https://minecraft.fandom.com/wiki/Anvil_mechanics#Combining_items

Each enchantment has a combine cost multiplier for an item containing the enchantment, or a book containing the enchantment, it would be very helpful to know that information

**Comment by dsfhdshdjtsb** [comment]
no
