### ISSUE TITLE
Shield enchantment mixins register even when disabled

### ISSUE THREAD

**Issue by Dekamir** [dsfhdshdjtsb/enchantments#26]
**Summary**
Shield enchantment mixins register even when disabled in the config. This causes mods like [Fixed Shields](https://www.curseforge.com/minecraft/mc-mods/fixed-shields) to crash at boot.

**Error messages**
[Log and Crash Report](https://gist.github.com/Dekamir/791f45493456b2e4024bf7496376c1d6)

**To Reproduce**
- Install this mod
- Install [Fixed Shields](https://www.curseforge.com/minecraft/mc-mods/fixed-shields)
- Start instance

**Comment by dsfhdshdjtsb** [comment]
completely removed shield enchants in latest version, as well as their corresponding mixins
