### ISSUE TITLE
Console Log Spam

### ISSUE THREAD

**Issue by Dekamir** [dsfhdshdjtsb/enchantments#27]
**Describe the bug**
The mod spams the console with a lot of logs (numbers, STDOUTs etc) when enchantments are in use.

**To Reproduce**
Hit enemies with enchantments.

**Screenshots**
![image](https://github.com/dsfhdshdjtsb/enchantments/assets/28929300/d27ffbe7-caed-4c8a-b014-3e055f4bbb01)
![image](https://github.com/dsfhdshdjtsb/enchantments/assets/28929300/4c86a38b-24aa-4cbd-9a4a-7a00045dea17)

**Comment by dsfhdshdjtsb** [comment]
these values were used for testing, ig I forgot to delete many of them. Fixed in latest version

**Comment by Dekamir** [comment]
Is this going to be backported to version 1.19.2, or is that version EOL?
