### ISSUE TITLE
[Bug Report] Lethality can drain 84 HP despite an armor difference of 17

### ISSUE THREAD

**Issue by RisingEclipse** [dsfhdshdjtsb/enchantments#28]
**Describe the bug**
Lethality is capable of draining a full 84 HP with a 17 armor difference at level 1

**Error messages**

**To Reproduce**
Utilize Gobber End armor with default stats + an additional 5 points of armor.

Get hit with a lethality 1 netherite sword with no other enchants

Die instantly

**Screenshots**

**Additional context**

**Comment by dsfhdshdjtsb** [comment]
what version are you playing on? This bug is patched in the most recent version

**Comment by dsfhdshdjtsb** [comment]
this bug was patched in version 2.14.5

**Comment by dsfhdshdjtsb** [comment]
lethality will be nerfed in the next patch
