### ISSUE TITLE
[Suggestion] Combo enchant no self-damage

### ISSUE THREAD

**Issue by Rad586** [dsfhdshdjtsb/enchantments#29]
**Describe the suggestion you'd like**
No self-damage using combo enchant.

**Describe the reasoning for the suggestion. Balance? Fixing a frustrating mechanic? New Idea?**
Combo enchant should be encouraged to deal damage multiple times, but the problem is, the more combos you do, the more lightning damage you'll receive, which discourages player from doing so.

**Comment by dsfhdshdjtsb** [comment]
this bug was patched in verison 2.14.5

**Comment by Rad586** [comment]
Will this fix be backported to 1.18.2?

**Comment by dsfhdshdjtsb** [comment]
probably not
