### ISSUE TITLE
Suggestion: Configurable mob enchantments

### ISSUE THREAD

**Issue by Dekamir** [dsfhdshdjtsb/enchantments#30]
**Describe the suggestion you'd like**
Allow configuring which enchantments mobs can spawn with.

**Describe the reasoning for the suggestion. Balance? Fixing a frustrating mechanic? New Idea?**
Mobs with Tremor create problems with mob farms and more.
Some Skeletons with Bow enchantments are sometimes too much.

**Comment by dsfhdshdjtsb** [comment]
As I said before in [this issue](https://github.com/dsfhdshdjtsb/enchantments/issues/22#issue-1570107182), this mod does not touch on game mechanics but only adds new enchants to the game
