### ISSUE TITLE
Disabling Lifesteal does not remove Lifesteal Cooldown effect on players

### ISSUE THREAD

**Issue by Dekamir** [dsfhdshdjtsb/enchantments#32]
This causes players to permanently have the Lifesteal Cooldown effect, even with the /effect clear command, as players need to hold a Lifesteal enchanted Sword to drain the cooldown, which they cannot do without Lifesteal enabled.

**To Reproduce**
- Enchant a Sword with Lifesteal.
- Quit game with Lifesteal Cooldown effect.
- Disable Lifesteal enchantment and restart game.
- Join world.

**Comment by dsfhdshdjtsb** [comment]
they can kill themselves
