### ISSUE TITLE
Lifesteal damages nearby players even when PVP is off

### ISSUE THREAD

**Issue by Dekamir** [dsfhdshdjtsb/enchantments#33]
**Describe the bug**
On PVP disabled server, Lifesteal still damages nearby players when hitting an entity

**To Reproduce**
1. Damage an entity (including inanimates like Minecarts)
2. Have a nearby player
3. Hit the entity with an item enchanted with Lifesteal

**Additional context**
This is especially a problem as Lifesteal works on inanimate entities like Minecarts and Boats. See #34 for more context.

**Comment by Aesthir** [comment]
Lifesteal also harms nearby villagers.

**Comment by dsfhdshdjtsb** [comment]
fixed for 1.20.5/1.21 update. Lifesteal harming villagers is expected behavior, however.
