### ISSUE TITLE
Lifesteal triggers on inanimate entities

### ISSUE THREAD

**Issue by Dekamir** [dsfhdshdjtsb/enchantments#34]
**Describe the bug**
Lifesteal gets triggered when hitting inanimate entities, such as Minecarts and Boats.
This causes other players and mobs to be damaged without intent.
This makes #33 more problematic.

**To Reproduce**
1. Have a nearby mob to monitor.
2. With a Lifesteal enchanted item, hit a Minecart or a Boat.

**Comment by dsfhdshdjtsb** [comment]
fixed for 1.20.2 update
