### ISSUE TITLE
Suggestion: Faster Arrow Despawn For Volley Enchant

### ISSUE THREAD

**Issue by NoobWithAUniqueName** [dsfhdshdjtsb/enchantments#35]
My Suggestion:

Volley is a really cool enchant, but it can cause lag for the game by the sheer amount of arrows that are existing at once. My suggestion to fix this is to cause the arrows summoned by Volley to have a 5 second despawn time.

The reason for this suggestion is that I was using the volley enchant with a really fast shooting bow (kinda my fault I know) which caused high tick lag, so I am suggesting a straightforward fix which is to make the arrows despawn faster.

**Comment by dsfhdshdjtsb** [comment]
good suggestions, ill consider doing this if I can figure out how
