### ISSUE TITLE
Using Rampage enchant causes server console to print "1" with every hit

### ISSUE THREAD

**Issue by FoxySophie** [dsfhdshdjtsb/enchantments#37]
**Describe the bug**
I'm running a server hosted on Bisect Hosting with a custom modpack which among others includes Combat Enchantments. Yesterday while I was playing with friends and also had the server console I noticed that suddenly there were constantly "1"s getting spammed. I managed to narrow it down to the Rampage 1 enchantment I had on my diamond sword, everytime I would hit an entity with it there would be two lines that just said "1" in the console.

**Error messages**
The message simply just says "1" everytime you hit a mob with that enchantment. 

**To Reproduce**
Enchant a weapon with Rampage and hit a mob. I don't know if the server console of the host has debugging enabled or something else, it does not show up in the log files, neither on the server nor client logs.

**Screenshots**
The debug message does not show up in the actual latest.log file so I can only provide a screenshot of the server console: https://i.vgy.me/9emNlx.png

**Additional context**
I had 3 different enchantments, all from Combat Enchantments, on my sword, but I narrowed it down to at least the Rampage enchantment. I have tried every other enchantment that can be applied to vanilla swords and none of them showed the same behaviour as Rampage.

**Comment by dsfhdshdjtsb** [comment]
fixed
