### ISSUE TITLE
[Suggestion] make combat enchants exclusive to the enchanting table

### ISSUE THREAD

**Issue by yesn0t** [dsfhdshdjtsb/enchantments#9]
**Describe the suggestion you'd like**
I'd like to have librarian villager trades not altered by this mod, so that they only trade vanilla enchanted books

**Describe the reasoning for the suggestion. Balance? Fixing a frustrating mechanic? New Idea?**
Using the enchanting table we can narrow down which enchantments to get based on which weapon/armour piece we enchant,  
this isn't the case with librarian villagers : they trade any and all books which combined with the number of enchantments this mod adds, makes it very difficult to get the desired book trade.  
This could be a togglable command option or gamerule if possible x)

**Additional context**
the wording of this suggestion includes loot tables of chests... could that be considered as well ?

**Comment by dsfhdshdjtsb** [comment]
I see your point, however, this mod is meant just to add more enchantments, but not change enchanting mechanics. This would be a great standalone addon/mod that someone else could make, but for now, I think I will keep things as is

**Comment by yesn0t** [comment]
fair enough, when i opened this issue i didn't understand how enchantments work in minecraft x)
so adding new enchantments makes them show up everywhere (loot tables, trading, enchanting table) and it wasn't a deliberate decision.
If you do know a way or any other mods to customise which enchantments appear where, i would love to know as well

**Comment by dsfhdshdjtsb** [comment]
Not aware of a mod, but getting the desired enchanting book from a villager is pretty easy. Just repeatedly place/remove the villager's lectern to reset his trades until you get the desired book.
